# Generated by Django 3.1.5 on 2023-01-10 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(max_length=255)),
                ('taxa_plataforma', models.FloatField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('codigoImovel', models.BigAutoField(primary_key=True, serialize=False)),
                ('limite_hospedes', models.PositiveIntegerField()),
                ('banheiros', models.PositiveIntegerField(default='1')),
                ('animais', models.BooleanField(default=True)),
                ('valor_limpeza', models.FloatField()),
                ('data_ativacao', models.DateField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('codigoReserva', models.BigAutoField(primary_key=True, serialize=False)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('preco_total', models.FloatField()),
                ('comentario', models.CharField(max_length=255)),
                ('hospedes', models.PositiveIntegerField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True, null=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khanto.anuncio')),
            ],
        ),
        migrations.AddField(
            model_name='anuncio',
            name='imovel',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='khanto.imovel'),
        ),
    ]
