# Generated by Django 3.1.5 on 2023-01-10 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khanto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(max_length=255)),
                ('taxa_plataforma', models.FloatField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='imovel',
            old_name='atualizado_em',
            new_name='data_atualizacao',
        ),
        migrations.RenameField(
            model_name='imovel',
            old_name='criado_em',
            new_name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='aceita_animais',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='codigo_imovel',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='quantidade_banheiros',
        ),
        migrations.AddField(
            model_name='imovel',
            name='animais',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='banheiros',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imovel',
            name='limite_hospedes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='valor_limpeza',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('preco_total', models.FloatField()),
                ('comentario', models.CharField(max_length=255)),
                ('hospedes', models.PositiveIntegerField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khanto.anuncio')),
            ],
        ),
        migrations.AddField(
            model_name='anuncio',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khanto.imovel'),
        ),
    ]
